name: SwiftLint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SwiftLint:
    runs-on: [self-hosted, macOS] # ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        run: swiftlint --strict
